## Week 2 - Quiz: Neural Network Basics

<br/>**1.**
What does a neuron compute?

**A neuron computes a linear function (z = Wx + b) followed by an activation function**

<br/>**2.**
Which of these is the "Logistic Loss"?

**$\mathcal{L}^{(i)}(\hat{y}^{(i)}, y^{(i)}) = -(y^{(i)} log(\hat{y}^{(i)}) + (1 - y^{(i)} log(1-\hat{y}^{(i)}))$**

<br/>**3.**
Suppose img is a (32,32,3) array, representing a 32x32 image with 3 color channels red, green and blue. How do you reshape this into a column vector?

**x = img.reshape((32*32*3,1))**

<br/>**4.**
Consider the two following random arrays "a" and "b":

In [21]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b
c

array([[-2.00060113, -2.75438757, -1.88601545],
       [ 0.97963243,  0.2702494 , -0.62825015]])

What will be the shape of "c"?

**c.shape = (2, 3)**

<br/>**5.**
Consider the two following random arrays "a" and "b":

In [22]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b
c

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

What will be the shape of "c"?

**The computation cannot happen because the sizes don't match. It's going to be "Error"!**

<br/>**6.**
Suppose you have $n_x$ input features per example. Recall that $X = [x^{(1)} x^{(2)} ... x^{(m)}]$. What is the dimension of X?

**$(n_x, m)$**

<br/>**7.**
Recall that "np.dot(a,b)" performs a matrix multiplication on a and b, whereas "a*b" performs an element-wise multiplication.

Consider the two following random arrays "a" and "b":

In [20]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
c

array([[ -9.47527248, -13.222109  ,  -1.96327569, ..., -20.15367905,
         -6.78990503, -16.86838997],
       [  7.07462541,  -7.28093308,  -8.02209861, ..., -12.4397062 ,
          8.63488354, -12.3094558 ],
       [ 15.94439257, -17.47023687,  14.73795766, ..., -14.91190613,
         -1.72037606, -16.23511997],
       ...,
       [ -9.07249843,  -8.3976266 ,   9.45337074, ..., -13.41105635,
         19.84728877,  14.07284579],
       [  3.78244329,  12.83332968,   8.92382308, ...,  -7.29034148,
         20.81174299,  -9.48153355],
       [ 14.0714253 , -12.3026664 ,  -5.85874531, ...,  -1.65300768,
         -5.15503997,   0.23501744]])

What is the shape of c?

**c.shape = (12288, 45)**

<br/>**8.**
Consider the following code snippet:

In [ ]:
# a.shape = (3,4)
# b.shape = (4,1)

for i in range(3):
  for j in range(4):
    c[i][j] = a[i][j] + b[j]

How do you vectorize this?

**c = a + b.T**

<br/>**9.**
Consider the following code:

In [19]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[-2.56861525, -2.10075837, -2.22654102],
       [-0.38354457, -0.30996374, -0.18436241],
       [-0.02195005, -0.01291612,  0.12447733]])

What will be c? (If you’re not sure, feel free to run this in python to find out).

**This will invoke broadcasting, so b is copied three times to become (3,3), and *∗ is an element-wise product so c.shape will be (3, 3)**

<br/>**10.**
Consider the following computation graph.

![picture alt](https://i.ibb.co/Wv5PN13/Fal-Vl3yg-Eeega-Q4-NYTd-ESg-7a0184575b8bdc47f8c3f29601302cb8-Screen-Shot-2017-08-08-at-6-13-59-PM.png)

What is the output J?

**J = (a - 1) * (b + c)**