## Week 4 - Quiz: Reading Files with Open

<br/>**1.**
consider the following text file Example1.txt:

This is line 1

This is line 2

This is line 3

What is the output of the following lines of code:

In [ ]:
with open("Example1.txt","r") as file1:  
    FileContent=file1.read()    
    print(FileContent)

**This is line 1**

**This is line 2**

**This is line 3**

<br/>**2.**
consider the file object File1, how would you read the first line of text.

**File1.readline ()**

<br/>**3.**
Consider the following line of code:

In [ ]:
with open(example1,"r") as file1:

**read**

## Week 4 - Quiz: Writing files with open

<br/>**1.**
Consider the following line of code:

In [ ]:
with open(example1,"w") as file1:

**write**

<br/>**2.**
What do the following lines of code do?

In [ ]:
with open("Example.txt","a") as writefile:
    writefile.write("This is line A\n")
    writefile.write("This is line B\n")

**Append the file "Example.txt"**

<br/>**3.**
What do the following lines of code do?

In [ ]:
with open("Example3.txt","w") as file1: 
    
file1.write("This is line C\n")

**read**

## Week 4 - Quiz: Pandas

<br/>**1.**
What is the result of applying the following method df.head(), to the dataframe df

**prints the first 5 rows of the dataframe**

<br/>**2.**
consider the dataframe df how would you access the element in the 2nd row and 1st column

**df.ix[1,0]** (ix is deprecated)

**df.iloc[1,0]**

<br/>**3.**
what function would you use to load a csv file in Pandas

**read_csv**

## Week 4 - Quiz: One Dimensional Numpy

<br/>**1.**
what is the result of the following lines of code:

In [2]:
import numpy as np
a=np.array([0,1,0,1,0])
b=np.array([1,0,1,0,1])
a*b

array([0, 0, 0, 0, 0])

**array([0, 0, 0, 0, 0])**

<br/>**2.**
what is the result of the following lines of code:

In [3]:
a=np.array([-1,1])
b=np.array([1,1])
np.dot(a,b) 

0

**0**

<br/>**3.**
what is the result of the following lines of code:

In [4]:
a=np.array([1,1,1,1,1])
a+10 

array([11, 11, 11, 11, 11])

**array([11, 11, 11, 11, 11])**

## Week 4 - Quiz: Two Dimensional Numpy

<br/>**1.**
What is the value of Z after the following code is run:

In [7]:
import numpy as np
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y

**array([[1, 1],[1, 1]])**

<br/>**2.**
what values does the variable out take if the following lines of code are run:

In [10]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

**array([1, 2])**

<br/>**3.**
What is the value of Z after the following code is run:

In [12]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y)

**array([[2, 1],[1, 2]])**